
<div class="article">
	<header class="top-bar">
		<h1>Chantage</h1>
	</header>
</div>
<form method="post">
    <div class="input-group">
        <input id="btn-input" name="content" type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." />
        <span class="input-group-btn">
        <button type ="submit" class="btn btn-invert btn-sm" id="btn-chat">Send</button>
        </span>
    </div>
</form>

    <div class="chat">   
      <div class="chat-history">
        <ul class="chat-ul">
	<?php require('apps/messages.php'); ?>
	</ul>
</div>
</div>
<script>
setInterval(function()
{
	$('.js_msg_list').load('index.php?page=messages&ajax');
}, 500);	
</script>