<form class="form-horizontal" method="post">
  <h1>Login</h1>
  <input type="hidden" name="action" value="login">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Login</label>

    <div class="col-sm-10">
      <input name="login" type="text" class="form-control" id="inputEmail3" placeholder="Login">
    </div>
  </div>
  <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Avatar</label>

      <div class="col-sm-10">
        <input name="avatar" type="email" class="form-control" id="inputEmail3" placeholder="Lien url">
      </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Modify</button>
    </div>
  </div>
    </div>
</form>