<!-- <h1>HEADER ADMIN</h1> -->
	<nav class="navbar navbar">
		<div class="navbar-header">
			<a class="navbar-brand" href="index.php">Accueil</a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li> <a href="index.php?page=home">Home</a> </li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=htmlentities($_SESSION['login'])?> <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="index.php?page=logout">Logout</a></li>
					<li><a href="index.php?page=logout">Modify</a></li>
				</ul>
			</li>
		</ul>
	</nav>