<form class="form-horizontal" method="post">
  <input type="hidden" name="action" value="login">

<div class="form-group">
      <div class="col-sm-10">
      <label for="login">Login</label>
      <input type="text" class="form-control" id="login" name="login" placeholder="Login" >
  </div>
</div>

    
<div class="form-group">
    <div class="col-sm-10">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="Password" >
    </div>
</div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
</div>
</form>