

<div class="row message">
	<div class="col-sm-1">
		<img class="img-responsive user-photo" src="<?=htmlentities($message['avatar'])?>">
	</div>
	<div class="col-sm-2">
		<strong><?=htmlentities($message['login'])?></strong>
	</div>
	<div class="col-sm-7 msg_content">
		<?=htmlentities($message['content'])?>
	</div>
	<div class="col-sm-2">
		<span class="text-muted"><?=htmlentities($message['date'])?></span>
	</div>
</div>
	<div><hr></div>
