<form class="form-horizontal" method="post">
  <h1>Register</h1>
  <input type="hidden" name="action" value="register">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Login</label>

    <div class="col-sm-10">
      <input name="login" type="text" class="form-control" id="inputEmail3" placeholder="Login">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>

    <div class="col-sm-10">
      <input name="password1" type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>

    <div class="col-sm-10">
      <input name="password2" type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Email</label>

    <div class="col-sm-10">
      <input name="email" type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>

  <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Avatar</label>

      <div class="col-sm-10">
        <input name="avatar" type="text" class="form-control" id="inputEmail3" placeholder="Lien url">
      </div>
    </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
