<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="style/bootstrap.min.css">

		<link rel="stylesheet" type="text/css" href="style/style.css" />
		<title>MVC Exemple 1</title>
	</head>
	<body>
		<div class="container">
			
		
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
		
		</div>
	</body>
	<script src="js/jquery.js"></script>
	<script src="js/bootstrap.min.js"></script>
</html>