<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>MVC Exemple 1</title>
		<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="styles/style.css">
		<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
		<script src="bootstrap/js/jquery-3.1.1.min.js"></script>
		<script src="bootstrap/js/bootstrap.min.js"></script>
	</head>
	<body>
		<div class="container">
			
			<?php require('apps/header.php'); ?>
			<?php require('apps/container.php'); ?>
			<?php require('apps/footer.php'); ?>

		</div>
	</body>
	<script>
		$(function(){
			$("#addClass").click(function () {
          		$('#qnimate').addClass('popup-box-on');
            });
          
            $("#removeClass").click(function () {
          		$('#qnimate').removeClass('popup-box-on');
            });
  		})
  	</script>
</html>